FROM node:23-slim

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY .env ./.env

RUN npm install
RUN npm install && npm install --save-dev ts-node typescript

COPY . .

RUN npm run build

EXPOSE 10000

CMD ["npm", "run", "dev"]
